[package]
name = "flapjack"
version = "0.3.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
regex = "1"
prettytable-rs = "0.10.0"
thiserror = "1.0.50"

[workspace]
members = ["manual_tests/*"]
